name: Corley Dubrosa Customs
favicon: null
layout_spectrum: 0.960813
typography_spectrum: 0.31165353904106174
title: Corley Dubrosa Customs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#070707'
    - '#988b7c'
    - '#64564b'
    - '#008167'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
