name: Corley Dubrosa Customs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31165353904106174
title: Corley Dubrosa Customs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#24211e'
    - '#ffffff'
    - '#91877c'
    - '#880000'
    - '#e06d00'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
